"""create initial tables

Revision ID: 2f17260d61d2
Revises: 
Create Date: 2026-03-12 13:37:59.295597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f17260d61d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('rag_metadata',
    sa.Column('doc_id', sa.String(length=255), nullable=False),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index(op.f('ix_rag_metadata_doc_id'), 'rag_metadata', ['doc_id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('rag_chunks',
    sa.Column('chunk_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.String(length=255), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['rag_metadata.doc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_rag_chunks_chunk_index'), 'rag_chunks', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_rag_chunks_doc_id'), 'rag_chunks', ['doc_id'], unique=False)
    op.create_table('rag_embeddings',
    sa.Column('embed_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.String(length=255), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_vector', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['rag_metadata.doc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('embed_id')
    )
    op.create_index(op.f('ix_rag_embeddings_chunk_index'), 'rag_embeddings', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_rag_embeddings_doc_id'), 'rag_embeddings', ['doc_id'], unique=False)
    op.create_table('tickets',
    sa.Column('ticket_id', sa.String(length=255), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('wrong_answer', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_tickets_conversation_id'), 'tickets', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    op.create_table('retrieval_logs',
    sa.Column('retrieval_log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('rewritten_query', sa.Text(), nullable=True),
    sa.Column('results_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('retrieval_log_id')
    )
    op.create_index(op.f('ix_retrieval_logs_message_id'), 'retrieval_logs', ['message_id'], unique=False)
    op.create_table('ticket_events',
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_ticket_events_ticket_id'), 'ticket_events', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_events_ticket_id'), table_name='ticket_events')
    op.drop_table('ticket_events')
    op.drop_index(op.f('ix_retrieval_logs_message_id'), table_name='retrieval_logs')
    op.drop_table('retrieval_logs')
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_conversation_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_rag_embeddings_doc_id'), table_name='rag_embeddings')
    op.drop_index(op.f('ix_rag_embeddings_chunk_index'), table_name='rag_embeddings')
    op.drop_table('rag_embeddings')
    op.drop_index(op.f('ix_rag_chunks_doc_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_chunk_index'), table_name='rag_chunks')
    op.drop_table('rag_chunks')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_rag_metadata_doc_id'), table_name='rag_metadata')
    op.drop_table('rag_metadata')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
